
spring:
  redis:
    host: 192.168.0.120
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-wait: 3000
        max-idle: 300
  datasource:
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zkr?useUnicode=true&amp&characterEncoding=utf8&amp&serverTimezone=GMT%2b8
  cache:
    type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:dao/*.xml
  type-aliases-package: com.example.redis.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
